version: '3.9'
services: 
  my-fastapi-service:
    container_name: whos-my-ta
    build: 
      context: .
      dockerfile: Dockerfile
    image: zainab_image:lastest
    cpus: 1
    mem_limit: 1024m
    ports:
      - "4568:4568"
